module.exports = {
    'add':[(a,b) =>a + b,2],
    'and':[(a,b)=>a&&b,2],
    'append':[(a,b)=>[...b,a],2],
    'bitand':[(a,b)=>a&b,2],
    'bitnot':[(a)=>~a,1],
    'bitor':[(a,b)=>a|b,2],
    'ceil':[Math.ceil,1],
    'char':[String.fromCharCode,1],
    'charcode':[a=>a.charCodeAt(),1],
    'double':[a=>a*2,1],
    'duplicate': [(a)=>[a,a],1,1],
    'floor':[a=>a-a%1,1],
    'half':[a=>a/2,1],
    'index': [(a,b)=>b[a],2],
    'iterate':[(a) => [...a],1,1],
    'maybe': [() => Math.random() < 0.5,0],
    'multiply':[(a,b)=> a * b, 2],
    'not':[(a)=>!a,1],
    'or':[(a,b)=>a||b,2],
    'pair':[(a,b)=>[b,a],2],
    'prepend':[(a,b)=>[a,...b],2],
    'print':[console.log,1],
    'quadruple':[a=>a*4,1],
    'quarter':[a=>a/4,1],
    'randfloat':[Math.random,0],
    'randint':[a=>~~(Math.random() * a),1],
    'randminmax':[(a,b)=>(Math.random() * Math.abs(a-b) + (b>a?a:b)),2],
    'random':[a=>a[~~(Math.random * a.length)],1],
    'repeat':[(a,b) => b.repeat(a), 2],
    'replace':[(a,b,c) => c.replaceAll(b,a),3],
    'sum':[a=>a.reduce(this.add[0]),1],
    'swap': [(a,b) => [b,a],2,1],
    'third':[a=>a/3,1],
    'triple':[a=>a*3,1],
    'wrap':[() => stack, 0],
}